### PR TITLE
CI: Add fedora33 for gcc10

### LINKED ISSUE #824: Spack recipe failed to build with gcc 10 (and 4.9)
On quartz I cloned spack master and configured it to use `gcc/10.2`. Building flux-sched@0.15 failed with

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'
6 errors found in build log:
     720                     from /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp:39:
     721    /g/g92/churavy1/spack/opt/spack/linux-rhel7-broadwell/gcc-10.2.1/boost-1.76.0-aysbkz6dx3n5k4kdpsgiycsnzbvw7wxw/include/boost/detail/iterator.hpp:13:1: note: '#pragma message: This header is deprecated. Use <iterator> instead.
            '
     722       13 | BOOST_HEADER_DEPRECATED("<iterator>")
     723          | ^~~~~~~~~~~~~~~~~~~~~~~
     724      CXXLD    grug2dot
     725    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp: In function 'std::shared_ptr<Flux::resource_model::resource_context_t> init_resourc
            e_query(int, char**)':
  >> 726    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp:721:21: error: 'DBL_MAX' was not declared in this scope
     727      721 |     ctx->perf.min = DBL_MAX;
     728          |                     ^~~~~~~
     729    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp:46:1: note: 'DBL_MAX' is defined in header '<cfloat>'; did you forget to '#include <
            cfloat>'?
     730       45 | #include "config.h"
     731      +++ |+#include <cfloat>
     732       46 | #endif
  >> 733    make[4]: *** [resource_query-resource-query.o] Error 1
     734    make[4]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build/resource/utilities'
  >> 735    make[3]: *** [all-recursive] Error 1
     736    make[3]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build/resource/utilities'
  >> 737    make[2]: *** [all-recursive] Error 1
     738    make[2]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build/resource'
  >> 739    make[1]: *** [all-recursive] Error 1
     740    make[1]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build'
  >> 741    make: *** [all] Error 2
See build log for details:
  /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-build-out.txt
==> Error: flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j: ProcessError: Command exited with status 2:
    'make' '-j16'
==> Error: flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j: Package was not installed
==> Updating view at /g/g92/churavy1/src/DaggerExamples/Flux/.spack-env/view
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```

### PR DESCRIPTION
**Pull request by SteVwonder**
Closes #824

### CODE REVIEW

**Comment by dongahn** [comment]
LGTM.

**Review by dongahn — APPROVED** [review]
