### ISSUE TITLE
Spack recipe failed to build with gcc 10 (and 4.9)

### ISSUE THREAD

**Issue by vchuravy** [flux-framework/flux-sched#824]
On quartz I cloned spack master and configured it to use `gcc/10.2`. Building flux-sched@0.15 failed with

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'
6 errors found in build log:
     720                     from /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp:39:
     721    /g/g92/churavy1/spack/opt/spack/linux-rhel7-broadwell/gcc-10.2.1/boost-1.76.0-aysbkz6dx3n5k4kdpsgiycsnzbvw7wxw/include/boost/detail/iterator.hpp:13:1: note: '#pragma message: This header is deprecated. Use <iterator> instead.
            '
     722       13 | BOOST_HEADER_DEPRECATED("<iterator>")
     723          | ^~~~~~~~~~~~~~~~~~~~~~~
     724      CXXLD    grug2dot
     725    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp: In function 'std::shared_ptr<Flux::resource_model::resource_context_t> init_resourc
            e_query(int, char**)':
  >> 726    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp:721:21: error: 'DBL_MAX' was not declared in this scope
     727      721 |     ctx->perf.min = DBL_MAX;
     728          |                     ^~~~~~~
     729    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/resource/utilities/resource-query.cpp:46:1: note: 'DBL_MAX' is defined in header '<cfloat>'; did you forget to '#include <
            cfloat>'?
     730       45 | #include "config.h"
     731      +++ |+#include <cfloat>
     732       46 | #endif
  >> 733    make[4]: *** [resource_query-resource-query.o] Error 1
     734    make[4]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build/resource/utilities'
  >> 735    make[3]: *** [all-recursive] Error 1
     736    make[3]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build/resource/utilities'
  >> 737    make[2]: *** [all-recursive] Error 1
     738    make[2]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build/resource'
  >> 739    make[1]: *** [all-recursive] Error 1
     740    make[1]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-src/spack-build'
  >> 741    make: *** [all] Error 2
See build log for details:
  /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j/spack-build-out.txt
==> Error: flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j: ProcessError: Command exited with status 2:
    'make' '-j16'
==> Error: flux-sched-0.15.0-uo2zab2mblvjrxb7br7o5dnqloj5cg7j: Package was not installed
==> Updating view at /g/g92/churavy1/src/DaggerExamples/Flux/.spack-env/view
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
```

**Comment by vchuravy** [comment]
Same issue with `4.9.3`

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

6 errors found in build log:
     583                     from /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/resource/utilities/resource-query.cpp:39:
     584    /g/g92/churavy1/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.76.0-azc7qknkn2yy2xzt3gnqbzcqq5mt7bzj/include/boost/detail/iterator.hpp:13:67: note: #pragma message: This header is deprecated. Use <iterator> instead.
     585     BOOST_HEADER_DEPRECATED("<iterator>")
     586                                                                       ^
     587      CXXLD    grug2dot
     588    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/resource/utilities/resource-query.cpp: In function 'std::shared_ptr<Flux::resource_model::resource_context_t> init_resourc
            e_query(int, char**)':
  >> 589    /var/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/resource/utilities/resource-query.cpp:721:21: error: 'DBL_MAX' was not declared in this scope
     590         ctx->perf.min = DBL_MAX;
     591                         ^
  >> 592    make[4]: *** [resource_query-resource-query.o] Error 1
     593    make[4]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/spack-build/resource/utilities'
  >> 594    make[3]: *** [all-recursive] Error 1
     595    make[3]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/spack-build/resource/utilities'
  >> 596    make[2]: *** [all-recursive] Error 1
     597    make[2]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/spack-build/resource'
  >> 598    make[1]: *** [all-recursive] Error 1
     599    make[1]: Leaving directory `/tmp/churavy1/spack-stage/spack-stage-flux-sched-0.15.0-hnjqdbccv5dvyyggqbit45iygeqdtm7o/spack-src/spack-build'
  >> 600    make: *** [all] Error 2

```
